### ISSUE TITLE
Create ADMozaikLayout in xib or Storyboard

### ISSUE THREAD

**Issue by radekwilczak** [Antondomashnev/ADMozaicCollectionViewLayout#17]
It would be great to have posibility to create ADMozaikLayout from xib or Storyboard.

Now, we have init?(coder aDecoder: NSCoder) but then we are not able to set up correctly rowHeight and columns.

**Comment by Antondomashnev** [comment]
Hi @radekwilczak it would be a good addition. I will try to take a look on it soon. Also I encourage you to submit a PR with this enhancement, this would be awesome 😄

**Comment by radekwilczak** [comment]
IMHO the simple solution is to make geometryInfo's setter public.

**Comment by Antondomashnev** [comment]
@radekwilczak the new release `3.1.0` is out 🚀
