### ISSUE TITLE
Header workaround

### ISSUE THREAD

**Issue by klabusta** [Antondomashnev/ADMozaicCollectionViewLayout#19]
Great pod, thanks! Do you plan to implement headers/footers anytime soon? Do you have a workaround solution for a header until this is implemented? 

I'm stuck here. Thanks!

**Comment by Antondomashnev** [comment]
Hi @klabusta, I'm planning to add this support but I can not really plan how soon at the moment. I would be really happy if you submit a PR with this feature 😄 

As a workaround there is one solution come to my mind: create a cell which looks like header or footer.

**Comment by klabusta** [comment]
Hi @Antondomashnev, I was considering that as a workaround. Only problem I see, is that my header needs a flexible height. With a fixed rowHeight for my mozaic layout, this doesn't seem easily possible. Or can I change the rowHeight just for one 'row'?

**Comment by Antondomashnev** [comment]
> can I change the rowHeight just for one 'row'?

@klabusta, unfortunately nope, but there is a crazy workaround for this. 
Imagine you have a height of the smallest cell is 44 points and height of header is 22 points, 
you can set the row height for 22 points, which will make a header be possible and the smallest cell becomes the cell of height of two row heights.

Let me know if the proposed workaround is understandable 😄

**Comment by klabusta** [comment]
Too bad this won't work. The header has a dynamic height, so I can't even guarantee it to be a multiple of rowHeight. I've forked and added top spacing. Which is really hacky, but will serve well until headers are possible. https://github.com/klabusta/ADMozaicCollectionViewLayout/blob/96b21ec48d4eda129dbe6db3d5fa1fe01ffbcbd4/ADMozaikCollectionViewLayout/Private/ADMozaikLayoutGeometry.swift

**Comment by Antondomashnev** [comment]
I will really try to find time soon to think about better way to handle it 😄

**Comment by Antondomashnev** [comment]
@klabusta Good news the new release is available 🚀 
Unfortunately, I had to do some breaking changes, but there is a [document](https://github.com/Antondomashnev/ADMozaicCollectionViewLayout/blob/master/Docs/4_Migration_guide.md) that should help you to ease the transition.

**Comment by klabusta** [comment]
Awesome. Thanks
