### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by klabusta** [Antondomashnev/ADMozaicCollectionViewLayout#22]
I'm getting a build error (only in our CI tool, not in XCode):

`Pods/ADMozaicCollectionViewLayout/ADMozaikCollectionViewLayout/Private/ADMozaikLayoutAttributes.swift:[102,39] 'Error' is not convertible to 'CustomStringConvertible'; did you mean to use 'as!' to force downcast?
    »                     fatalError((error as CustomStringConvertible).description)`

**Comment by Antondomashnev** [comment]
Hi @klabusta, sorry somehow I missed your issue. I think this is because the new swift release deprecated the function that `ADMozaikCollectionViewLayout` uses. I will prepare a new release with the update soon.

**Comment by Antondomashnev** [comment]
It's released in 4.0.1 🚀
