### ISSUE TITLE
Carthage can't build library

### ISSUE THREAD

**Issue by v-yatsevich** [Antondomashnev/ADMozaicCollectionViewLayout#30]
The library needs some pods installed, but by default, it's downloaded without pods, and build crashes. If I try to install pods manually in carthage checkouts folder, it still crashes with "The sandbox is not in sync with the Podfile.lock." error.
There is no cache for swift 4 version, so, carthage doesn't use it too

**Comment by Antondomashnev** [comment]
@AntiVIRUZ hi, try again with the `4.0.4` release.
