### ISSUE TITLE
The Order of Cells changes.

### ISSUE THREAD

**Issue by Omeesh** [Antondomashnev/ADMozaicCollectionViewLayout#32]
I have data in a particular order and want to show three types of cell i.e Full, Half and Quarter. The collectionView works fine most of the times but sometimes the quarter cell which should be shown at last appears at some random place in collection view.

**Comment by Antondomashnev** [comment]
Hi @Omeesh could you please provide the example app so I can debug it?

**Comment by Omeesh** [comment]
@Antondomashnev 

See the Attached image.
Issue is Quat 4 should come after Full 1. But it is coming after Quat 3 because there is some space vacant.
![1530279995410 jpeg](https://user-images.githubusercontent.com/35801305/42095777-36329bec-7bd1-11e8-9450-53c1989fae85.jpg)

**Comment by Omeesh** [comment]
I was able to resolve the issue by creating a transparent quarter size Cell in vacant place.

**Comment by Antondomashnev** [comment]
@Omeesh I think the use case is valid, I'll try to make an update with the support of keeping order.
