### ISSUE TITLE
Keep order not getting in version 4.0.4

### ISSUE THREAD

**Issue by swapnil-winjit** [Antondomashnev/ADMozaicCollectionViewLayout#35]
I installed version 4.0.4 but id dint have Delegate & content mode for keep order.
So how should I will have Content mode options as per document .
@Antondomashnev @cyrilchandelier

**Comment by Antondomashnev** [comment]
@swapnil-winjit thanks for raising it, unfortunately, I think I forgot to make a proper release. I'll do it by today or tomorrow. Until than you can point the `pod` to master:
`pod 'ADMozaicCollectionViewLayout' :git => 'https://github.com/Antondomashnev/ADMozaicCollectionViewLayout.git', :branch => 'master'`

**Comment by Antondomashnev** [comment]
@swapnil-winjit release is ready 🚀
