### ISSUE TITLE
how to get width dynamically ?

### ISSUE THREAD

**Issue by arsanjani** [Antondomashnev/ADMozaicCollectionViewLayout#4]
hi there,
Due to the device size & orientation, how can i get proper width dynamically ?
i divide column count with collection-view width size but results not as expected.

**Comment by Antondomashnev** [comment]
Hi @arsanjani, if I understood you correct, you want to get the width of collection view dynamically, not the device size. In that case you can use `self.collectionView.collectionViewLayout.collectionViewContentSize()`, please let me know if it helps.

**Comment by arsanjani** [comment]
hi @Antondomashnev , thanks for your reply
i mean that if orientation changed, AdMosaicLayout not adopted to new size automatically and cells not fit the screen width. is there any way to activate autolayout in adMosicLayout cells ?

**Comment by Antondomashnev** [comment]
@arsanjani unfortunately, currently it is not possible. But I'm more than happy to see PR with that feature=) Otherwise I'll try to find out the solution and I've created the respected task #5.
