### ISSUE TITLE
Swift 3 Compatibility ?

### ISSUE THREAD

**Issue by arsanjani** [Antondomashnev/ADMozaicCollectionViewLayout#6]
hi there,
is this library compatible with swift 3 && Xcode 8 or need an update ?

**Comment by Antondomashnev** [comment]
Hi @arsanjani it's on my todo list, the update will be hopefully this weekend.

**Comment by Antondomashnev** [comment]
@arsanjani the release is ready: [2.0.0](https://github.com/Antondomashnev/ADMozaicCollectionViewLayout/releases/tag/2.0.0)
